language: scala
scala:
  - "2.11.7"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.mvn/
script:
  - sbt ++${TRAVIS_SCALA_VERSION} clean coverage test
after_success:
  - sbt coveralls
